_target_: compare_representations.MeasureSelection
measures:
  - rsm_norm_diff
  - eigenspace_overlap_score
  - aligned_cossim
  - orthogonal_procrustes
  - representational_similarity_analysis
  - centered_kernel_alignment
