- _target_: llmcomp.measures.orthogonal_procrustes
  _partial_: true

- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.normalize_matrix_norm
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.orthogonal_procrustes
    _partial_: true

- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.center_columns
      _partial_: true
    - _target_: llmcomp.measures.utils.normalize_matrix_norm
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.orthogonal_procrustes
    _partial_: true
