- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.center_columns
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.rank_similarity
    _partial_: true

- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.center_columns
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.joint_rank_jaccard_similarity
    _partial_: true

- _target_: llmcomp.measures.imd_score
  _partial_: true

- _target_: llmcomp.measures.geometry_score
  _partial_: true
