- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.center_columns
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.orthogonal_procrustes
    _partial_: true

- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs:
    - _target_: llmcomp.measures.utils.center_columns
      _partial_: true
  similarity_func:
    _target_: llmcomp.measures.magnitude_difference
    _partial_: true

- _target_: llmcomp.measures.uniformity_difference
  _partial_: true

- _target_: llmcomp.measures.rsm_norm_diff
  _partial_: true

- _target_: llmcomp.measures.distance_correlation
  _partial_: true

- _target_: llmcomp.measures.utils.Pipeline
  preprocess_funcs: []
  similarity_func:
    _target_: llmcomp.measures.representational_similarity_analysis
    _partial_: true
    inner: euclidean
    outer: euclidean
