- _target_: llmcomp.measures.orthogonal_procrustes
  _partial_: true

- _target_: llmcomp.measures.magnitude_difference
  _partial_: true

- _target_: llmcomp.measures.magnitude_nrmse
  _partial_: true
