excluded_measures:
- GeometryScore
# - IMDScore
# - RSMNormDifference
# - DistanceCorrelation
# - RSA
# - RTD
threads: 1
cache_to_disk: true
cache_to_mem: false
only_extract_reps: false
rerun_nans: false
experiments:
- name: Vision Gauss R18 C100 Experiments
  type: GroupSeparationExperiment
  representation_dataset: Gauss_Off_CIFAR100DataModule
  filter_key_vals:
    train_dataset:
    - Gauss_Max_CIFAR100DataModule
    - Gauss_M_CIFAR100DataModule
    - Gauss_S_CIFAR100DataModule
    architecture:
    - VGG11
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    domain: VISION
  grouping_keys:
  - train_dataset
  separation_keys:
  - architecture
raw_results_filename: c100_augment_vgg11.parquet
table_creation:
  save_full_df: true
  full_df_filename: c100_augment_vgg11.csv
  save_aggregated_df: false
  row_index: similarity_measure
  columns:
  - identifier
  - representation_dataset
  - quality_measure
  - architecture
  value_key: value
  filename: c100_augment_vgg11.xlsx
