parquets_to_merge:
  - "c100_randomlabel_vgg11.parquet"
  - "c100_randomlabel_vgg19.parquet"
  - "c100_randomlabel_r18.parquet"
  - "c100_randomlabel_r34.parquet"
  - "c100_randomlabel_r101.parquet"
  - "c100_shortcut_vgg11.parquet"
  - "c100_shortcut_vgg19.parquet"
  - "c100_shortcut_r18.parquet"
  - "c100_shortcut_r34.parquet"
  - "c100_shortcut_r101.parquet"
  - "c100_output_vgg11.parquet"
  - "c100_output_vgg19.parquet"
  - "c100_output_resnet18.parquet"
  - "c100_output_resnet34.parquet"
  - "c100_output_resnet101.parquet"
  - "c100_monotonicity_vgg11.parquet"
  - "c100_monotonicity_vgg19.parquet"
  - "c100_monotonicity_r18.parquet"
  - "c100_monotonicity_r34.parquet"
  - "c100_monotonicity_r101.parquet"
  - "c100_augment_vgg11.parquet"
  - "c100_augment_vgg19.parquet"
  - "c100_augment_r18.parquet"
  - "c100_augment_r34.parquet"
  - "c100_augment_r101.parquet"
output_parquet: "c100_preliminary_merged.parquet"
