excluded_measures:
- GeometryScore
- IMDScore
- RSMNormDifference
- DistanceCorrelation
- RSA
- CKA
threads: 1
cache_to_disk: true
cache_to_mem: false
only_extract_reps: false
rerun_nans: false
experiments:
- name: Vision Short Cut Correlation Experiments
  type: GroupSeparationExperiment
  representation_dataset: CIFAR100
  filter_key_vals:
    train_dataset:
    - RandomLabel_100_C100_DataModule
    - RandomLabel_50_C100_DataModule
    - CIFAR100
    architecture:
    - ResNet18
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    domain: VISION
  grouping_keys:
  - train_dataset
  separation_keys:
  - architecture
raw_results_filename: C100_randomlabel_resnet18.parquet
table_creation:
  save_full_df: true
  full_df_filename: C100_randomlabel_resnet18.csv
  save_aggregated_df: true
  row_index: similarity_measure
  columns:
  - identifier
  - representation_dataset
  - quality_measure
  - architecture
  value_key: value
  filename: C100_randomlabel_resnet18.xlsx
