excluded_measures:
- GeometryScore
- PWCCA
threads: 1
cache_to_disk: true
cache_to_mem: false
only_extract_reps: false
rerun_nans: false
experiments:
- name: Vision Short Cut Correlation Experiments
  type: GroupSeparationExperiment
  representation_dataset: ColorDot_0_C100DataModule
  filter_key_vals:
    train_dataset:
    - ColorDot_100_C100DataModule
    - ColorDot_75_C100DataModule
    - ColorDot_0_C100DataModule
    architecture:
    - ViT_B32
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    domain: VISION
  grouping_keys:
  - train_dataset
  separation_keys:
  - architecture
raw_results_filename: c100_shortcut_vitb32.parquet
table_creation:
  save_full_df: true
  full_df_filename: c100_shortcut_vitb32.csv
  save_aggregated_df: false
  row_index: similarity_measure
  columns:
  - quality_measure
  - architecture
  value_key: value
  filename: c100_shortcut_vitb32.csv
