cache_to_disk: false
cache_to_mem: true
excluded_measures:
- GeometryScore
experiments:
- filter_key_vals:
    domain: GRAPHS
    identifier:
    - Normal
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    train_dataset:
    - flickr
  grouping_keys:
  - identifier
  name: output_correlation_test flickr
  representation_dataset: flickr
  separation_keys:
  - architecture
  type: OutputCorrelationExperiment
  use_acc_comparison: true
only_extract_reps: false
raw_results_filename: graphs_output_correlation_test_flickr.parquet
table_creation:
  columns:
  - quality_measure
  - architecture
  filename: graphs_output_correlation_test_flickr.csv
  full_df_filename: graphs_output_correlation_test_flickr_full.csv
  row_index: similarity_measure
  save_aggregated_df: false
  save_full_df: true
  value_key: value
threads: 1
