cache_to_disk: true
cache_to_mem: false
excluded_measures:
- RSMNormDifference
- IMDScore
- GeometryScore
- PWCCA
experiments:
- filter_key_vals:
    domain: GRAPHS
    identifier:
    - Normal
    - RandomLabels_25
    - RandomLabels_50
    - RandomLabels_75
    - RandomLabels_100
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    train_dataset:
    - flickr
  grouping_keys:
  - identifier
  name: label_test GroupSeparationExperiment flickr
  representation_dataset: flickr
  separation_keys:
  - architecture
  type: GroupSeparationExperiment
only_extract_reps: false
raw_results_filename: label_test_group_separation_flickr.parquet
table_creation:
  columns:
  - quality_measure
  - architecture
  filename: label_test_group_separation_flickr.csv
  full_df_filename: label_test_group_separation_flickr_full.csv
  row_index: similarity_measure
  save_aggregated_df: true
  save_full_df: true
  value_key: value
threads: 1
