excluded_measures:
- GeometryScore
- IMDScore
- RSMNormDifference
- DistanceCorrelation
- RSA
- CKA
threads: 1
cache_to_disk: true
cache_to_mem: false
only_extract_reps: false
rerun_nans: false
experiments:
- name: Monotonicity Experiment
  type: MonotonicityExperiment
  representation_dataset: ImageNet100
  filter_key_vals:
    train_dataset:
    - ImageNet100
    architecture:
    - ResNet18
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    domain: VISION
  grouping_keys:
  - train_dataset
  separation_keys:
  - architecture
raw_results_filename: in100_monotonicity_resnet18_imd.parquet
included_measures:
- IMDScore
