name: sst2 # huggingface load_dataset argument: path
config: # huggingface load_dataset argument: name
split: test
prompt_template: # promptsource template name

# Hyperparameters for the finetuning of BERT on this dataset
finetuning:
  num_labels: 2
  trainer:
    _target_: transformers.Trainer
    args:
      _target_: transformers.TrainingArguments
      output_dir: ${hydra:runtime.output_dir}
      overwrite_output_dir: true
      warmup_ratio: 0.1
      evaluation_strategy: steps
      eval_steps: 1000
      per_device_train_batch_size: 64
      per_device_eval_batch_size: 64
      seed: 123456789
  eval_dataset:
    - "validation"
