# Holds all information needed to run experiments.
excluded_measures:
  # - EigenspaceOverlapScore
  - GeometryScore
  - IMDScore
  # - LinearRegression
threads: 1
cache_to_disk: False
cache_to_mem: True
only_extract_reps: False
experiments:
  - name: NLP SST2 Correlation Experiments
    type: OutputCorrelationExperiment # Defines the type of experiment class to use
    use_acc_comparison: True
    representation_dataset: "sst2"
    filter_key_vals: # Only keeps models that have any of the values for the keys.
      identifier:
        - "Normal"
      train_dataset:
        - "sst2"
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      domain: NLP
    grouping_keys: # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
      - train_dataset
    separation_keys: # Creates a separate experiment for each unique value of the key.
      - architecture
raw_results_filename: correlation_nlp_standard_sst2.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: True
  full_df_filename: correlation_nlp_standard_sst2_full.csv
  # ---
  save_aggregated_df: False
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - quality_measure
    - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: nlp_standard_sst2.csv # Can be [.xlsx / .csv / .tex] file extension
