# Holds all information needed to run experiments.
excluded_measures:
  - SVCCA
  - PWCCA
  - EigenspaceOverlapScore
  - GeometryScore
  - IMDScore
  - LinearRegression
  - Gulp
  - AlignedCosineSimilarity
  - OrthogonalAngularShapeMetricCentered
  - OrthogonalProcrustesCenteredAndNormalized
  - ProcrustesSizeAndShapeDistance
  - RSMNormDifference
  - ConcentricityDifference
  - UniformityDifference
threads: 1
cache: True
only_extract_reps: False
experiments:
  - name: Gauss Noise Experiment
    type: GroupSeparationExperiment  # Defines the type of experiment class to use
    representation_dataset: "Gauss_Off_CIFAR10DataModule"
    filter_key_vals:  # Only keeps models that have any of the values for the keys.
      train_dataset:
        - Gauss_Max_CIFAR10DataModule
        - Gauss_L_CIFAR10DataModule
        - Gauss_M_CIFAR10DataModule
        - Gauss_S_CIFAR10DataModule
        - Gauss_Off_CIFAR10DataModule
      architecture:
        - ResNet18
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
      domain: VISION
    grouping_keys:  # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
      - train_dataset
    separation_keys:  # Creates a separate experiment for each unique value of the key.
      - architecture

table_creation:
  row_index: similarity_measure  # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - quality_measure
    - architecture
  value_key: value  # The key specifying the value that fills the table (non-header/index values)
  filename: vision_augment_quick_ones.xlsx  # Can be [.xlsx / .csv / .tex] file extension
