# Holds all information needed to run experiments.
excluded_measures:
  - PWCCA
  - GeometryScore
  - IMDScore
threads: 1
cache_to_disk: True
cache_to_mem: False
only_extract_reps: False
rerun_nans: True
experiments:
  - name: Vision Short Cut Correlation Experiments
    type: GroupSeparationExperiment # Defines the type of experiment class to use
    representation_dataset: "ColorDot_0_ImageNet100DataModule"
    filter_key_vals:  # Only keeps models that have any of the values for the keys.
      train_dataset:
        - ColorDot_100_ImageNet100DataModule
        - ColorDot_75_ImageNet100DataModule
        - ColorDot_50_ImageNet100DataModule
        - ColorDot_25_ImageNet100DataModule
        - ColorDot_0_ImageNet100DataModule
      architecture:
        - VGG11
        - VGG19
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
      domain: VISION
    grouping_keys: # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
      - train_dataset
    separation_keys: # Creates a separate experiment for each unique value of the key.
      - architecture
raw_results_filename: in100_shortcut.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: True
  full_df_filename: in100_shortcut.csv
  # ---
  save_aggregated_df: False
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - quality_measure
    - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: in100_shortcut.csv # Can be [.xlsx / .csv / .tex] file extension
