# Holds all information needed to run experiments.
included_measures:
  - CKA
threads: 1
cache_to_disk: True
cache_to_mem: True
only_extract_reps: True
experiments:
  - name: R18 IN100 Monotonicity
    type: SameLayerExperiment # Defines the type of experiment class to use
    representation_dataset: "ImageNet100"
    filter_key_vals:  # Only keeps models that have any of the values for the keys.
      train_dataset:
        - ImageNet100
      architecture:
        - ResNet18
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      domain: VISION
    separation_keys: # Creates a separate experiment for each unique value of the key.
      - architecture
raw_results_filename: in100_r18_monotonicity.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: True
  full_df_filename: vision_correlation_shortcut_debug_full.csv
  # ---
  save_aggregated_df: False
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - quality_measure
    - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: vision_shortcut_debug.csv # Can be [.xlsx / .csv / .tex] file extension
