# Holds all information needed to run experiments.
excluded_measures:
  - EigenspaceOverlapScore
  - GeometryScore
  - IMDScore
  - LinearRegression
threads: 1
cache_to_disk: False
cache_to_mem: True
only_extract_reps: False
experiments:
  - name: NLP Short Cut Experiments
    type: GroupSeparationExperiment # Defines the type of experiment class to use
    representation_dataset: "mnli_sc_rate0354"
    filter_key_vals: # Only keeps models that have any of the values for the keys.
      train_dataset:
        - "mnli_sc_rate0354"
        - "mnli_sc_rate05155"
        - "mnli_sc_rate0677"
        - "mnli_sc_rate08385"
        - "mnli_sc_rate1"
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
      domain: NLP
    grouping_keys: # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
      - train_dataset
    separation_keys: # Creates a separate experiment for each unique value of the key.
      - architecture
raw_results_filename: nlp_shortcuts_mnli.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: True
  full_df_filename: nlp_sc_mnli_full.csv
  # ---
  save_aggregated_df: True
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - quality_measure
    - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: nlp_shortcut_mnli.csv # Can be [.xlsx / .csv / .tex] file extension
